// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_McFO5U--cYvtGF30KXHq5rYol20vag8',
    appId: '1:1093623940846:web:803e368fd9b81bf47c55ff',
    messagingSenderId: '1093623940846',
    projectId: 'firebase-cli-1',
    authDomain: 'fir-cli-1-7c07b.firebaseapp.com',
    storageBucket: 'firebase-cli-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4FfJ9GsjzhOnBaSrtr0jPM1GzN6DCx5I',
    appId: '1:1093623940846:android:2d02c4e49fab07487c55ff',
    messagingSenderId: '1093623940846',
    projectId: 'firebase-cli-1',
    storageBucket: 'firebase-cli-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqlJsaGKNu8AN_m8mmB0ckIRsbHaHGcjs',
    appId: '1:1093623940846:ios:6ee30262d023d7e97c55ff',
    messagingSenderId: '1093623940846',
    projectId: 'firebase-cli-1',
    storageBucket: 'firebase-cli-1.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqlJsaGKNu8AN_m8mmB0ckIRsbHaHGcjs',
    appId: '1:1093623940846:ios:86a51586444a4cb17c55ff',
    messagingSenderId: '1093623940846',
    projectId: 'firebase-cli-1',
    storageBucket: 'firebase-cli-1.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
